// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdate() {
  return window['go']['main']['App']['ApplyUpdate']();
}

export function BroadcastVC(arg1) {
  return window['go']['main']['App']['BroadcastVC'](arg1);
}

export function CheckForUpdate(arg1) {
  return window['go']['main']['App']['CheckForUpdate'](arg1);
}

export function DeleteBroadcastVC(arg1, arg2) {
  return window['go']['main']['App']['DeleteBroadcastVC'](arg1, arg2);
}

export function ExportCredentialJSON(arg1) {
  return window['go']['main']['App']['ExportCredentialJSON'](arg1);
}

export function GenerateHTMLReport(arg1, arg2) {
  return window['go']['main']['App']['GenerateHTMLReport'](arg1, arg2);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetBroadcastStatus(arg1) {
  return window['go']['main']['App']['GetBroadcastStatus'](arg1);
}

export function GetDID() {
  return window['go']['main']['App']['GetDID']();
}

export function GetLedger() {
  return window['go']['main']['App']['GetLedger']();
}

export function GetMnemonic() {
  return window['go']['main']['App']['GetMnemonic']();
}

export function GetProfileIndex() {
  return window['go']['main']['App']['GetProfileIndex']();
}

export function GetProfileInfo() {
  return window['go']['main']['App']['GetProfileInfo']();
}

export function GetWalletStatus() {
  return window['go']['main']['App']['GetWalletStatus']();
}

export function GetWorkspaceFiles(arg1) {
  return window['go']['main']['App']['GetWorkspaceFiles'](arg1);
}

export function ImportMnemonic(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportMnemonic'](arg1, arg2, arg3);
}

export function InitWallet(arg1, arg2) {
  return window['go']['main']['App']['InitWallet'](arg1, arg2);
}

export function IsAutoStartEnabled() {
  return window['go']['main']['App']['IsAutoStartEnabled']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function LoadSessionIgnores() {
  return window['go']['main']['App']['LoadSessionIgnores']();
}

export function LockVault() {
  return window['go']['main']['App']['LockVault']();
}

export function MigrateWallet(arg1, arg2) {
  return window['go']['main']['App']['MigrateWallet'](arg1, arg2);
}

export function ResetBroadcastVC(arg1, arg2) {
  return window['go']['main']['App']['ResetBroadcastVC'](arg1, arg2);
}

export function ResolveDroppedPath(arg1) {
  return window['go']['main']['App']['ResolveDroppedPath'](arg1);
}

export function RestartApp() {
  return window['go']['main']['App']['RestartApp']();
}

export function RestoreDataFromSync() {
  return window['go']['main']['App']['RestoreDataFromSync']();
}

export function RevokeCredential(arg1) {
  return window['go']['main']['App']['RevokeCredential'](arg1);
}

export function SaveConfig(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function SaveProfileInfo(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveProfileInfo'](arg1, arg2, arg3);
}

export function SaveSessionIgnores(arg1, arg2) {
  return window['go']['main']['App']['SaveSessionIgnores'](arg1, arg2);
}

export function SaveToFile(arg1, arg2) {
  return window['go']['main']['App']['SaveToFile'](arg1, arg2);
}

export function SaveWindowState(arg1) {
  return window['go']['main']['App']['SaveWindowState'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function StartWatchdog() {
  return window['go']['main']['App']['StartWatchdog']();
}

export function ToggleAutoStart(arg1) {
  return window['go']['main']['App']['ToggleAutoStart'](arg1);
}

export function TriggerMint(arg1, arg2, arg3) {
  return window['go']['main']['App']['TriggerMint'](arg1, arg2, arg3);
}

export function UnlockWallet(arg1) {
  return window['go']['main']['App']['UnlockWallet'](arg1);
}

export function UpdateIgnoredPatterns(arg1) {
  return window['go']['main']['App']['UpdateIgnoredPatterns'](arg1);
}

export function VerifyChain() {
  return window['go']['main']['App']['VerifyChain']();
}

export function VerifyCredential(arg1) {
  return window['go']['main']['App']['VerifyCredential'](arg1);
}

export function WipeIdentity() {
  return window['go']['main']['App']['WipeIdentity']();
}
