// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExportCredentialJSON(arg1:string):Promise<string>;

export function ExportIdentityBundle(arg1:string):Promise<string>;

export function GetDID():Promise<string>;

export function GetLedger():Promise<Array<main.LedgerEntry>>;

export function GetWalletStatus():Promise<string>;

export function GetWorkspaceFiles(arg1:string):Promise<Array<string>>;

export function ImportIdentityBundle(arg1:string,arg2:string):Promise<string>;

export function InitWallet(arg1:string,arg2:string):Promise<string>;

export function LoadConfig():Promise<main.Config>;

export function MigrateWallet(arg1:string,arg2:string):Promise<string>;

export function RevokeCredential(arg1:string):Promise<string>;

export function SaveConfig(arg1:Array<string>,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function SaveToFile(arg1:string,arg2:string):Promise<string>;

export function SelectDirectory():Promise<string>;

export function StartWatchdog():Promise<string>;

export function TriggerMint(arg1:Array<string>,arg2:string):Promise<string>;

export function UnlockWallet(arg1:string):Promise<string>;

export function VerifyChain():Promise<string>;

export function VerifyCredential(arg1:string):Promise<string>;
