// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportCredentialJSON(arg1) {
  return window['go']['main']['App']['ExportCredentialJSON'](arg1);
}

export function ExportIdentityBundle(arg1) {
  return window['go']['main']['App']['ExportIdentityBundle'](arg1);
}

export function GetDID() {
  return window['go']['main']['App']['GetDID']();
}

export function GetLedger() {
  return window['go']['main']['App']['GetLedger']();
}

export function GetWalletStatus() {
  return window['go']['main']['App']['GetWalletStatus']();
}

export function GetWorkspaceFiles(arg1) {
  return window['go']['main']['App']['GetWorkspaceFiles'](arg1);
}

export function ImportIdentityBundle(arg1, arg2) {
  return window['go']['main']['App']['ImportIdentityBundle'](arg1, arg2);
}

export function InitWallet(arg1, arg2) {
  return window['go']['main']['App']['InitWallet'](arg1, arg2);
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function MigrateWallet(arg1, arg2) {
  return window['go']['main']['App']['MigrateWallet'](arg1, arg2);
}

export function RevokeCredential(arg1) {
  return window['go']['main']['App']['RevokeCredential'](arg1);
}

export function SaveConfig(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveToFile(arg1, arg2) {
  return window['go']['main']['App']['SaveToFile'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function StartWatchdog() {
  return window['go']['main']['App']['StartWatchdog']();
}

export function TriggerMint(arg1, arg2) {
  return window['go']['main']['App']['TriggerMint'](arg1, arg2);
}

export function UnlockWallet(arg1) {
  return window['go']['main']['App']['UnlockWallet'](arg1);
}

export function VerifyChain() {
  return window['go']['main']['App']['VerifyChain']();
}

export function VerifyCredential(arg1) {
  return window['go']['main']['App']['VerifyCredential'](arg1);
}
