// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BroadcastVC(arg1:string):Promise<string>;

export function ExportCredentialJSON(arg1:string):Promise<string>;

export function ExportIdentityBundle():Promise<string>;

export function ExportSanitizedJSON(arg1:string):Promise<string>;

export function ExportVHBBackup(arg1:string,arg2:string):Promise<string>;

export function GenerateHTMLReport(arg1:string,arg2:string):Promise<string>;

export function GenerateHistoricReports():Promise<void>;

export function GetBroadcastStatus(arg1:string):Promise<Array<main.BroadcastPublication>>;

export function GetDID():Promise<string>;

export function GetLedger():Promise<Array<main.LedgerEntry>>;

export function GetMnemonic():Promise<string>;

export function GetProfileIndex():Promise<string>;

export function GetWalletStatus():Promise<string>;

export function GetWorkspaceFiles(arg1:string):Promise<Array<string>>;

export function ImportIdentityBundle(arg1:string,arg2:string):Promise<string>;

export function ImportMnemonic(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ImportVHBBackup(arg1:string):Promise<string>;

export function InitWallet(arg1:string,arg2:string):Promise<string>;

export function IsAutoStartEnabled():Promise<boolean>;

export function LoadConfig():Promise<main.Config>;

export function LoadSessionIgnores():Promise<Record<string, Array<string>>>;

export function LockVault():Promise<string>;

export function MigrateWallet(arg1:string,arg2:string):Promise<string>;

export function ResolveDroppedPath(arg1:string):Promise<string>;

export function RestoreDataFromSync():Promise<string>;

export function RevokeCredential(arg1:string):Promise<string>;

export function SaveConfig(arg1:Array<string>,arg2:string,arg3:string,arg4:string,arg5:string,arg6:Array<string>,arg7:string):Promise<string>;

export function SaveSessionIgnores(arg1:string,arg2:Array<string>):Promise<string>;

export function SaveToFile(arg1:string,arg2:string):Promise<string>;

export function SelectDirectory():Promise<string>;

export function StartWatchdog():Promise<string>;

export function SyncHistoricLedger(arg1:string):Promise<string>;

export function ToggleAutoStart(arg1:boolean):Promise<void>;

export function TriggerMint(arg1:Array<string>,arg2:string):Promise<string>;

export function UnlockWallet(arg1:string):Promise<string>;

export function UpdateIgnoredPatterns(arg1:Array<string>):Promise<string>;

export function VerifyChain():Promise<string>;

export function VerifyCredential(arg1:string):Promise<string>;
